packages:
  - packages/*
catalogMode: prefer
catalogs:
  build:
    tsdown: ^0.21.2
  ci:
    publint: ^0.3.18
  cli:
    yargs: ^18.0.0
  dev:
    '@antfu/eslint-config': ^7.7.2
    '@antfu/ni': ^28.3.0
    '@types/smtp-server': ^3.5.12
    '@vitest/coverage-v8': ^4.1.0
    bumpp: ^10.4.1
    eslint: ^10.0.3
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
    smtp-server: ^3.18.1
    taze: ^19.10.0
    typescript: ^6.0.0
    vitest: ^4.1.0
  lib:
    add: ^2.0.6
    defu: ^6.1.4
    emailjs: ^5.0.0
    ofetch: ^1.5.1
    ufo: ^1.6.3
    zod: ^4.3.6
  types:
    '@types/node': ^25.5.0
    '@types/yargs': ^17.0.35

shellEmulator: true

trustPolicy: no-downgrade
