allowBuilds:
  simple-git-hooks: true
catalogMode: prefer
minimumReleaseAgeExclude:
  - '@types/node@25.9.0'

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
catalogs:
  build:
    tsdown: ^0.22.0
  ci:
    publint: ^0.3.21
  cli:
    yargs: ^18.0.0
  dev:
    '@antfu/eslint-config': ^9.0.0
    '@antfu/ni': ^30.1.0
    '@types/smtp-server': ^3.5.13
    '@vitest/coverage-v8': ^4.1.6
    bumpp: ^11.1.0
    eslint: ^10.4.0
    eslint-plugin-format: ^2.0.1
    lint-staged: ^17.0.5
    simple-git-hooks: ^2.13.1
    smtp-server: ^3.18.4
    taze: ^19.12.0
    typescript: ^6.0.3
    vitest: ^4.1.6
  lib:
    add: ^2.0.6
    defu: ^6.1.7
    emailjs: ^5.0.0
    ofetch: ^1.5.1
    ufo: ^1.6.4
    zod: ^4.4.3
  types:
    '@types/node': ^25.9.0
    '@types/yargs': ^17.0.35
